#ifndef ONBOARDTEST_TESTDECLERATIONS_H
#define ONBOARDTEST_TESTDECLERATIONS_H

typedef enum
{
  // Add your tests here
  E_TEST_ERROR_NULL_PTR_ARG,
  E_TEST_ERROR_DIVIDE_BY_ZERO,
  E_TEST_ERROR_WORK_WITH_UNINITIALIZED_PTRS,
  E_TEST_ERROR_ILLEGAL_INSTRUCTION_EXECUTION,
  E_TEST_ERROR_ILLEGAL_ADDRESS_EXECUTION,
  E_TEST_ERROR_NULL_PTR_FUNCTION_EXECUTION,
  E_TEST_ERROR_READ_FROM_BAD_ADDRESS,
  E_TEST_ERROR_IMPRECISE_FAULT,
  E_TEST_ERROR_STACKING_EXCEPTION_ERROR,
  E_TEST_ERROR_WRITE_TO_INVALID_ROM_ADDRESS,
  E_TEST_ERROR_TRIGGER_STACK_OVERFLOW,

  // Exercises
  E_TEST_EXERCISE_1,
  E_TEST_LAST_ENTRY
} OnBoardTest_Test_e;

typedef void (*test_function_ptr)(void);

#endif // ONBOARDTEST_TESTDECLERATIONS_H
