#ifndef ONBOARDTEST_TESTDECLERATIONS_H
#define ONBOARDTEST_TESTDECLERATIONS_H

typedef enum
{
  // Add your tests here
  E_TEST_ERROR_NULL_PTR_ARG,
  E_TEST_ERROR_DIVIDE_BY_ZERO,
  E_TEST_ERROR_WRITE_TO_NULL,
  E_TEST_ERROR_ILLEGAL_INSTRUCTION_EXECUTION,
  E_TEST_ERROR_ILLEGAL_ADDRESS_EXECUTION,
  E_TEST_ERROR_NULL_PTR_FUNCTION_EXECUTION,
  E_TEST_LAST_ENTRY
} OnBoardTest_Test_e;

typedef void (*test_function_ptr)(void);

#endif // ONBOARDTEST_TESTDECLERATIONS_H
